# Generation of a permutation basis

* Author: Mauricio Fernández
* Last update: 2021-10-05

Table of contents

* [1. Example for n = 6](#1.-Example-for-n=6)
* [2. Load basis](#2.-Load-basis)

## Description
The present notebook demonstrates the generation of permutation bases for spaces of isotropic tensor of order $n$ in 3D. A small database with permutation bases up to $n = 12$ is available, from which bases can be loaded.

In [1]:
import numpy as np

import odf_cen_av.permutation_basis as pb
import odf_cen_av.tensor_numpy as tn

## 1. Example for n=6

For $n=6$, return the dimension of the space of isotropic tensors.

In [2]:
n = 6
d = tn.diso(n)
print(d)

15


Generate a permutation basis based on the random generation strategy.

In [3]:
P = pb.random(n)
print(P)

[[3 5 0 1 4 2]
 [0 2 4 5 1 3]
 [4 0 2 1 3 5]
 [5 3 0 4 1 2]
 [1 2 5 3 0 4]
 [2 5 1 3 4 0]
 [3 4 5 1 0 2]
 [5 1 4 2 3 0]
 [5 4 2 1 0 3]
 [2 1 0 4 3 5]
 [2 4 3 0 5 1]
 [0 1 4 2 5 3]
 [0 3 2 1 4 5]
 [0 4 1 5 3 2]
 [4 5 2 3 0 1]]


Generate basic isotropic tensor for $n=6$: $B_{ijklmn} = \delta_{ij}\delta_{kl}\delta_{mn}$ corresponds to `B`

In [4]:
B = tn.Biso(n)
print(B.shape)

(3, 3, 3, 3, 3, 3)


Based on permutation basis `P` from above, compute metric matrix and return determinant. The determinant of the generated set of isotropic tensors does not vanish, i.e., the set is a basis of the space of isotropic tensors for $n=6$.

In [5]:
m = np.array([
    [tn.sp(np.transpose(B, p1), np.transpose(B, p2)) for p2 in P]
    for p1 in P
])
print(m)
print(np.linalg.det(m))

[[27.  9.  9.  3.  3.  9.  9.  3.  3.  3.  9.  3.  3.  3.  9.]
 [ 9. 27.  3.  9.  9.  3.  3.  9.  3.  9.  3.  3.  3.  3.  9.]
 [ 9.  3. 27.  9.  9.  3.  9.  3.  3.  3.  3.  9.  3.  9.  3.]
 [ 3.  9.  9. 27.  3.  9.  3.  9.  3.  3.  3.  9.  9.  3.  3.]
 [ 3.  9.  9.  3. 27.  9.  3.  3.  9.  9.  3.  3.  3.  9.  3.]
 [ 9.  3.  3.  9.  9. 27.  3.  3.  9.  3.  9.  3.  9.  3.  3.]
 [ 9.  3.  9.  3.  3.  3. 27.  9.  9.  9.  3.  3.  9.  3.  3.]
 [ 3.  9.  3.  9.  3.  3.  9. 27.  9.  3.  9.  3.  3.  9.  3.]
 [ 3.  3.  3.  3.  9.  9.  9.  9. 27.  3.  3.  9.  3.  3.  9.]
 [ 3.  9.  3.  3.  9.  3.  9.  3.  3. 27.  9.  9.  9.  3.  3.]
 [ 9.  3.  3.  3.  3.  9.  3.  9.  3.  9. 27.  9.  3.  9.  3.]
 [ 3.  3.  9.  9.  3.  3.  3.  3.  9.  9.  9. 27.  3.  3.  9.]
 [ 3.  3.  3.  9.  3.  9.  9.  3.  3.  9.  3.  3. 27.  9.  9.]
 [ 3.  3.  9.  3.  9.  3.  3.  9.  3.  3.  9.  3.  9. 27.  9.]
 [ 9.  9.  3.  3.  3.  3.  3.  3.  9.  3.  3.  9.  9.  9. 27.]]
1.6070775839999875e+19


Alternative function for same check. Option `info=True` prints the computed determinant.

In [6]:
pb.check_det(P, info=True)

...Computed determinant:
1.6070775839999875e+19


True

Save generate permutation basis to database

In [7]:
path = pb.save_to_data(P)
print(path)

...saved odf_cen_av/data/pbasis6.txt
odf_cen_av/data/pbasis6.txt


## 2. Load basis

See list of available permutation bases.

In [8]:
paths = pb.list_available()
print(paths)

List of available permutation bases:
	odf_cen_av/data/pbasis4.txt
	odf_cen_av/data/pbasis5.txt
	odf_cen_av/data/pbasis6.txt
	odf_cen_av/data/pbasis7.txt
	odf_cen_av/data/pbasis8.txt
	odf_cen_av/data/pbasis9.txt
	odf_cen_av/data/pbasis10.txt
	odf_cen_av/data/pbasis11.txt
	odf_cen_av/data/pbasis12.txt
['odf_cen_av/data/pbasis4.txt', 'odf_cen_av/data/pbasis5.txt', 'odf_cen_av/data/pbasis6.txt', 'odf_cen_av/data/pbasis7.txt', 'odf_cen_av/data/pbasis8.txt', 'odf_cen_av/data/pbasis9.txt', 'odf_cen_av/data/pbasis10.txt', 'odf_cen_av/data/pbasis11.txt', 'odf_cen_av/data/pbasis12.txt']


For `n`, load permutation basis, if available.

In [9]:
n = 8
P = pb.load(n)
print(P.shape)

(91, 8)


Check if the generated set of isotropic tensors for on `P` for `n` yields a basis (based on determinant of metric matrix).

In [10]:
pb.check_det(P)

True