
# Generation of a permutation basis

* Author: Mauricio Fernández
* Last update: 2020-06-14

Table of contents

* [1. Example for n = 6](#1.-Example-for-n=6)
* [2. Load basis](#2.-Load-basis)

## Description
The present notebook demonstrates the generation of permutation basis for spaces of isotropic tensor of order $n$ in 3D. A small database with permutation bases up to $n = 12$ is available, from which bases can be loaded.

In [1]:
import numpy as np

import src.CentralODFAverage as cen
import src.TensorCalculusNumpy as tn

## 1. Example for n=6

For $n=6$, return the dimension of the space of isotropic tensors.

In [2]:
n = 6
d = tn.diso(n)
print(d)

15


Generate a permutation basis based on the random generation strategy.

In [3]:
P = cen.pbasis_random(n)
print(P)

[[4 2 0 1 3 5]
 [3 0 5 4 2 1]
 [5 0 3 1 2 4]
 [1 4 3 0 2 5]
 [4 0 3 1 5 2]
 [4 1 2 5 0 3]
 [1 3 2 4 5 0]
 [2 5 3 0 1 4]
 [5 4 0 2 3 1]
 [4 2 3 0 5 1]
 [5 2 4 0 3 1]
 [4 5 1 3 0 2]
 [0 2 3 1 5 4]
 [3 0 2 1 4 5]
 [0 1 2 3 4 5]]


Generate basic isotropic tensor for $n=6$: $B_{ijklmn} = \delta_{ij}\delta_{kl}\delta_{mn}$ corresponds to `B`

In [4]:
B = tn.Biso(n)
print(B.shape)

(3, 3, 3, 3, 3, 3)


Based on permutation basis `P` from above, compute metric matrix and return determinant. The determinant of the generated set of isotropic tensors does not vanish, i.e., the set is a basis of the space of isotropic tensors for $n=6$.

In [5]:
m = np.array([
    [tn.sp(np.transpose(B, p1), np.transpose(B, p2)) for p2 in P]
    for p1 in P
])
print(m)
print(np.linalg.det(m))

[[27.  9.  9.  3.  3.  9.  9.  3.  3.  3.  9.  3.  3.  3.  9.]
 [ 9. 27.  3.  9.  9.  3.  3.  9.  3.  9.  3.  3.  3.  3.  9.]
 [ 9.  3. 27.  9.  9.  3.  9.  3.  3.  3.  3.  9.  3.  9.  3.]
 [ 3.  9.  9. 27.  3.  9.  3.  9.  3.  3.  3.  9.  9.  3.  3.]
 [ 3.  9.  9.  3. 27.  9.  3.  3.  9.  9.  3.  3.  3.  9.  3.]
 [ 9.  3.  3.  9.  9. 27.  3.  3.  9.  3.  9.  3.  9.  3.  3.]
 [ 9.  3.  9.  3.  3.  3. 27.  9.  9.  9.  3.  3.  9.  3.  3.]
 [ 3.  9.  3.  9.  3.  3.  9. 27.  9.  3.  9.  3.  3.  9.  3.]
 [ 3.  3.  3.  3.  9.  9.  9.  9. 27.  3.  3.  9.  3.  3.  9.]
 [ 3.  9.  3.  3.  9.  3.  9.  3.  3. 27.  9.  9.  9.  3.  3.]
 [ 9.  3.  3.  3.  3.  9.  3.  9.  3.  9. 27.  9.  3.  9.  3.]
 [ 3.  3.  9.  9.  3.  3.  3.  3.  9.  9.  9. 27.  3.  3.  9.]
 [ 3.  3.  3.  9.  3.  9.  9.  3.  3.  9.  3.  3. 27.  9.  9.]
 [ 3.  3.  9.  3.  9.  3.  3.  9.  3.  3.  9.  3.  9. 27.  9.]
 [ 9.  9.  3.  3.  3.  3.  3.  3.  9.  3.  3.  9.  9.  9. 27.]]
1.607077583999999e+19


Alternative function for same check. Option `info=True` prints the computed determinant.

In [6]:
cen.pbasis_check_det(P, info=True)

...Computed determinant:
1.607077583999999e+19


True

Save generate permutation basis to database

In [7]:
path = cen.pbasis_save(P)
print(path)

...saved src/data/pbasis6.txt
src/data/pbasis6.txt


## 2. Load basis

See list of available permutation bases.

In [8]:
paths = cen.pbasis_list()
print(paths)

List of available permutation bases:
	src/data/pbasis4.txt
	src/data/pbasis5.txt
	src/data/pbasis6.txt
	src/data/pbasis7.txt
	src/data/pbasis8.txt
	src/data/pbasis9.txt
	src/data/pbasis10.txt
	src/data/pbasis11.txt
	src/data/pbasis12.txt
['src/data/pbasis4.txt', 'src/data/pbasis5.txt', 'src/data/pbasis6.txt', 'src/data/pbasis7.txt', 'src/data/pbasis8.txt', 'src/data/pbasis9.txt', 'src/data/pbasis10.txt', 'src/data/pbasis11.txt', 'src/data/pbasis12.txt']


For `n`, load permutation basis, if available.

In [9]:
n = 8
P = cen.pbasis_load(n)
print(P.shape)

(91, 8)


Check if the generated set of isotropic tensors for on `P` for `n` yields a basis (based on determinant of metric matrix).

In [10]:
cen.pbasis_check_det(P)

True