# Demo 2: Computation of $\mathbb{D}_{\langle 2r \rangle \alpha}$ tensors

* Author: Mauricio Fernández
* Last update: 2020-06-14

Table of contents

* [1. Example for r = 2](#1.-Example-for-r=2)
* [2. Example for r = 3](#2.-Example-for-r=3)
* [3. List of available tensors and loading](#3.-List-of-available-tensors-and-loading)

## Description
The present notebook demonstrates FIXME.

In [1]:
import numpy as np

import src.CentralODFAverage as cen
import src.TensorCalculusNumpy as tn

## 1. Example for r=2

For $r=2$, compute tensors $\mathbb{D}_{\langle 2r \rangle \alpha}$ based on numerical integration for $\alpha = 0,1,\dots,r$, i.e., $\mathbb{D}_{\langle 4 \rangle 0}$, $\mathbb{D}_{\langle 4 \rangle 1}$ and $\mathbb{D}_{\langle 4 \rangle 2}$. The matrix `Dv` contains the tensors as flattened vectors in its columns.

In [2]:
r = 2
Dv = cen.Dv_compute(r)
print(Dv.shape)

...Loading permutation basis
2020-06-30 22:52:43.929872
...Constructing basis
2020-06-30 22:52:43.950717
...Computing ONB
2020-06-30 22:52:43.950717
...Computing integrals
2020-06-30 22:52:43.967531
...Done
2020-06-30 22:52:44.078568
(81, 3)


Reshape to full tensors (index $\alpha$ is then first index in `Ds`).

In [3]:
Ds = Dv.T.reshape([-1] + (2*r)*[3,])
Ds.shape

(3, 3, 3, 3, 3)

Check that computed tensors match the known analytical results for $r=2$, i.e., $\mathbb{D}_{\langle 4 \rangle 0} = \mathbb{I}_{\langle 4 \rangle}^\mathrm{iso}$ (identity on isotropic 2nd-order tensors), $\mathbb{D}_{\langle 4 \rangle 1} = \mathbb{I}_{\langle 4 \rangle}^\mathrm{a}$ (identity on anti-symmetric 2nd-order tensors) and
$\mathbb{D}_{\langle 4 \rangle 2} = \mathbb{I}_{\langle 4 \rangle}^\mathrm{h}$ (identity on harmonic 2nd-order tensors).

In [4]:
IdI = tn.tp(tn.I2,tn.I2)
Iiso = IdI/3
I4 = np.transpose(IdI,(0,2,1,3))
Is = (I4+np.transpose(I4,(0,1,3,2)))/2
Ia = (I4-np.transpose(I4,(0,1,3,2)))/2
Ih = Is-Iiso
print('Deviation of D_{<4>0} from Iiso:\t%.4e' % tn.nf(Ds[0]-Iiso))
print('Deviation of D_{<4>1} from Ia:\t\t%.4e' % tn.nf(Ds[1]-Ia))
print('Deviation of D_{<4>2} from Ih:\t\t%.4e' % tn.nf(Ds[2]-Ih))

Deviation of D_{<4>0} from Iiso:	1.7416e-16
Deviation of D_{<4>1} from Ia:		3.9950e-16
Deviation of D_{<4>2} from Ih:		2.7459e-16


## 2. Example for r=3

Compute

In [5]:
r = 3
Dv = cen.Dv_compute(r)
Ds = Dv.T.reshape([-1] + (2*r)*[3,])

...Loading permutation basis
2020-06-30 22:52:44.244723
...Constructing basis
2020-06-30 22:52:44.267884
...Computing ONB
2020-06-30 22:52:44.270906
...Computing integrals
2020-06-30 22:52:44.275374
...Done
2020-06-30 22:52:45.597813


Check that tensors $\mathbb{D}_{\langle 2r \rangle \alpha}$ are orthogonal, NOT normalized. The terms on the diagonal of `m` correspond to $\mathbb{D}_{\langle 2r \rangle \alpha} \cdot \mathbb{D}_{\langle 2r \rangle \alpha}$, which reflects the dimension of the corresponding eigenspace, for which $\mathbb{D}_{\langle 2r \rangle \alpha}$ is the corresponding projector.

In [6]:
m = np.array([[tn.sp(D1, D2) for D2 in Ds] for D1 in Ds])
print(m)

[[ 1.00000000e+00  6.99362745e-16 -7.77156117e-16 -1.69040176e-15]
 [ 6.99362745e-16  9.00000000e+00 -3.22311622e-15  1.38777878e-15]
 [-7.77156117e-16 -3.22311622e-15  1.00000000e+01 -1.07552856e-15]
 [-1.69040176e-15  1.38777878e-15 -1.07552856e-15  7.00000000e+00]]


The trace of `m` then reflects the dimension of the space of $r$-th-order tensors, i.e., $3^r$.

In [7]:
np.trace(m) == 3**r

True

## 3. List of available tensors and loading

Print list of available tensors in database.

In [8]:
paths = cen.Dv_list()

List of available Dv:
	src/data/Dv4.txt
	src/data/Dv6.txt
	src/data/Dv8.txt
	src/data/Dv10.txt
	src/data/Dv12.txt


Check if tensors exists in database.

In [9]:
r = 3
check = cen.Dv_exist(r)
print(check)

True


In [10]:
r = 7
check = cen.Dv_exist(r)
print(check)

...corresponding Dv NOT available.
	Generate and save first.
List of available Dv:
	src/data/Dv4.txt
	src/data/Dv6.txt
	src/data/Dv8.txt
	src/data/Dv10.txt
	src/data/Dv12.txt
False


Load.

In [11]:
r = 4
Dv = cen.Dv_load(r)
print(Dv.shape)
print((3**(2*r), r+1))

(6561, 5)
(6561, 5)
