# Computation of $\mathbb{D}_{\langle 2r \rangle \alpha}$ tensors

* Author: Mauricio Fernández
* Last update: 2021-10-05

Table of contents

* [1. Example for r = 2](#1.-Example-for-r=2)
* [2. Example for r = 3](#2.-Example-for-r=3)
* [3. List of available tensors and loading](#3.-List-of-available-tensors-and-loading)

## Description
The present notebook demonstrates FIXME.

In [1]:
import numpy as np

import odf_cen_av.d_tensors as dt
import odf_cen_av.tensor_numpy as tn

## 1. Example for r=2

For $r=2$, compute tensors $\mathbb{D}_{\langle 2r \rangle \alpha}$ based on numerical integration for $\alpha = 0,1,\dots,r$, i.e., $\mathbb{D}_{\langle 4 \rangle 0}$, $\mathbb{D}_{\langle 4 \rangle 1}$ and $\mathbb{D}_{\langle 4 \rangle 2}$. The matrix `Dv` contains the tensors as flattened vectors in its columns.

In [2]:
r = 2
Dv = dt.Dv_compute(r)
print(Dv.shape)

...Loading permutation basis
2021-10-06 00:13:21.899250
...Constructing basis
2021-10-06 00:13:21.909237
...Computing ONB
2021-10-06 00:13:21.909237
...Computing integrals
2021-10-06 00:13:21.909237
...Done
2021-10-06 00:13:21.961139
(81, 3)


Reshape to full tensors (index $\alpha$ is then first index in `Ds`).

In [3]:
Ds = Dv.T.reshape([-1] + (2*r)*[3,])
Ds.shape

(3, 3, 3, 3, 3)

Check that computed tensors match the known analytical results for $r=2$, i.e., $\mathbb{D}_{\langle 4 \rangle 0} = \mathbb{I}_{\langle 4 \rangle}^\mathrm{iso}$ (identity on isotropic 2nd-order tensors), $\mathbb{D}_{\langle 4 \rangle 1} = \mathbb{I}_{\langle 4 \rangle}^\mathrm{a}$ (identity on anti-symmetric 2nd-order tensors) and
$\mathbb{D}_{\langle 4 \rangle 2} = \mathbb{I}_{\langle 4 \rangle}^\mathrm{h}$ (identity on harmonic 2nd-order tensors).

In [4]:
IdI = tn.tp(tn.I2,tn.I2)
Iiso = IdI/3
I4 = np.transpose(IdI,(0,2,1,3))
Is = (I4+np.transpose(I4,(0,1,3,2)))/2
Ia = (I4-np.transpose(I4,(0,1,3,2)))/2
Ih = Is-Iiso
print('Deviation of D_{<4>0} from Iiso:\t%.4e' % tn.nf(Ds[0]-Iiso))
print('Deviation of D_{<4>1} from Ia:\t\t%.4e' % tn.nf(Ds[1]-Ia))
print('Deviation of D_{<4>2} from Ih:\t\t%.4e' % tn.nf(Ds[2]-Ih))

Deviation of D_{<4>0} from Iiso:	1.5114e-16
Deviation of D_{<4>1} from Ia:		4.0020e-16
Deviation of D_{<4>2} from Ih:		4.9092e-16


## 2. Example for r=3

Compute

In [5]:
r = 3
Dv = dt.Dv_compute(r)
Ds = Dv.T.reshape([-1] + (2*r)*[3,])

...Loading permutation basis
2021-10-06 00:13:22.412204
...Constructing basis
2021-10-06 00:13:22.414227
...Computing ONB
2021-10-06 00:13:22.414227
...Computing integrals
2021-10-06 00:13:22.414227
...Done
2021-10-06 00:13:23.207198


Check that tensors $\mathbb{D}_{\langle 2r \rangle \alpha}$ are orthogonal, NOT normalized. The terms on the diagonal of `m` correspond to $\mathbb{D}_{\langle 2r \rangle \alpha} \cdot \mathbb{D}_{\langle 2r \rangle \alpha}$, which reflects the dimension of the corresponding eigenspace, for which $\mathbb{D}_{\langle 2r \rangle \alpha}$ is the corresponding projector.

In [6]:
m = np.array([[tn.sp(D1, D2) for D2 in Ds] for D1 in Ds])
print(m)

[[ 1.00000000e+00  4.53876318e-16 -4.99600361e-16 -2.42222669e-15]
 [ 4.53876318e-16  9.00000000e+00 -4.44089210e-16  4.44089210e-16]
 [-4.99600361e-16 -4.44089210e-16  1.00000000e+01  2.66453526e-15]
 [-2.42222669e-15  4.44089210e-16  2.66453526e-15  7.00000000e+00]]


The trace of `m` then reflects the dimension of the space of $r$-th-order tensors, i.e., $3^r$.

In [7]:
np.trace(m) == 3**r

True

## 3. List of available tensors and loading

Print list of available tensors in database.

In [8]:
paths = dt.Dv_list()

List of available Dv:
	odf_cen_av/data/Dv4.txt
	odf_cen_av/data/Dv6.txt
	odf_cen_av/data/Dv8.txt
	odf_cen_av/data/Dv10.txt
	odf_cen_av/data/Dv12.txt


Check if tensors exists in database.

In [9]:
r = 3
check = dt.Dv_exist(r)
print(check)

True


In [10]:
r = 7
check = dt.Dv_exist(r)
print(check)

...corresponding Dv NOT available.
	Generate and save first.
List of available Dv:
	odf_cen_av/data/Dv4.txt
	odf_cen_av/data/Dv6.txt
	odf_cen_av/data/Dv8.txt
	odf_cen_av/data/Dv10.txt
	odf_cen_av/data/Dv12.txt
False


Load.

In [11]:
r = 4
Dv = dt.Dv_load(r)
print(Dv.shape)
print((3**(2*r), r+1))

(6561, 5)
(6561, 5)
