# Quantitive texture analysis

* Author: Mauricio Fernández
* Last update: 2021-10-05

Table of contents

* [1. Minimization of epsilon^+](#1.-Minimization-of-epsilon^+)

## Description
The present notebook corresponds to the quantitative texture analysis example in the manuscript documented section 3.3 (minimization of $\epsilon^+$). The numerical optimizations take some time. The corresponding restuls can be found in the manuscript, section 3.3, Table 2..

In [1]:
import numpy as np

import odf_cen_av.texture as tex
import odf_cen_av.tensor_numpy as tn
import odf_cen_av.tensor_sympy as ts

## 1. Minimization of epsilon^+

Orientation data

In [2]:
nfori = 21
fori = 1 / nfori * np.ones(nfori)
omori = np.pi * np.linspace(0, 1, nfori)
Qori = [tn.rotm([1, 0, 0], omi) for omi in omori]
odata = [fori, Qori]

Tensor order $r$

In [3]:
r = 3

Check that needed ONB of harmonic tensors are available

In [4]:
tn.checkhonb(r)

Harmonic ONBs already generated up to tensor order 3


Optiimize $\epsilon^+$ with $m$ texture components

In [5]:
for m in [2, 3, 4]:
    print('\n----------------------------------------')
    print('\nNumber of components: %i' % m)
    res = tex.mineplus(odata, r=r, ncomponents=m, npointsLa=4)
    print('\nComponent concentrations')
    for ress in res[0]:
        print('\t%.4f' % ress)
    print('\nRotation axes (n_1,n_2,n_3) (in rows) of central orientations of corresponding component')
    print(res[1])
    print('\nRotation angles of central orientations of corresponding component')
    print(res[2])
    print('\nTexture eigenvalues (lambda_1,lambda_2,...) (in rows) of corresponding component')
    print(res[3])
    print('Check value of $\\epsilon^+$')
    Vori = tex.tc(odata, r)
    Vcen = tex.tccen(res)
    print('\t%.4f' % tex.epsilonplus(Vori, Vcen))


----------------------------------------

Number of components: 2
Min and max norms of texture coefficients of original ODF: 
	0.0476
	1.0000
Initial value of function (\epsilon^+): 
	42.9368
Optimization terminated successfully    (Exit mode 0)
            Current function value: 31.42852882684343
            Iterations: 72
            Function evaluations: 1434
            Gradient evaluations: 72

Component concentrations
	0.7572
	0.2428

Rotation axes (n_1,n_2,n_3) (in rows) of central orientations of corresponding component
[[ 1.00000000e+00 -9.40788152e-09 -1.33685362e-07]
 [-8.26846530e-05 -7.07117334e-01  7.07096232e-01]]

Rotation angles of central orientations of corresponding component
[1.57079639 3.14156685]

Texture eigenvalues (lambda_1,lambda_2,...) (in rows) of corresponding component
[[ 7.99046993e-01  5.17712784e-01  3.11018262e-01]
 [ 7.23538224e-07  2.00000000e-01 -1.42857143e-01]]
Check value of $\epsilon^+$
	31.4285

----------------------------------------

Numb

Depending on the current version of Sympy, Numpy and Scipy the user might get different results out of the numerical optimization. Therefore, the user may directly input concentrations, variables of central orientations and texture eigenvalues of interest and evaluate the bound $\epsilon^+$. This can be done in the present file based on the following lines of code.

$m$ = 2

In [6]:
component_concentrations = np.array([
    0.7572,
    0.2428
])
rotation_axes = np.array([
    [1.0000, 0.0000, 0.0000], 
    [0.0000, -0.7071, 0.7071]
])
rotation_angles = np.array([
    1.5708,
    3.1416
])
texture_eigenvalues = np.array([
    [0.7991, 0.5179, 0.3112], 
    [0.0000, 0.2000, -0.1429]
])

####################################

variables = [
    component_concentrations,
    rotation_axes,
    rotation_angles,
    texture_eigenvalues
]
texture_coefficients_original = tex.tc(odata, 3)
texture_coefficients_central = tex.tccen(variables)
eps = tex.epsilonplus(
    texture_coefficients_original,
    texture_coefficients_central
)
print('%.4f' % eps)

31.4283


$m = 3$

In [7]:
component_concentrations = np.array([
    0.4106,
    0.3875,
    0.2018
])
rotation_axes = np.array([
    [1, 0, 0],
    [1,0,0],
    [-0.8827,-0.0007,0.4700]
])
rotation_angles = np.array([
    2.4987, 
    1.2102,
    0
])
texture_eigenvalues = np.array([
    [0.9966, 0.9919, 0.9885], 
    [0.9920, 0.9952, 0.9931],
    [0.9508, 0.9410, 0.9578]
])

####################################

variables = [
    component_concentrations,
    rotation_axes,
    rotation_angles,
    texture_eigenvalues
]
texture_coefficients_original = tex.tc(odata, 3)
texture_coefficients_central = tex.tccen(variables)
eps = tex.epsilonplus(
    texture_coefficients_original,
    texture_coefficients_central
)
print('%.4f' % eps)

4.1760


$m = 4$

In [8]:
component_concentrations = np.array([
    0.3070,
    0.3861,
    0.3069
])
rotation_axes = np.array([
    [1,0,0],
    [1,0,0],
    [1,0,0]
])
rotation_angles = np.array([
    2.7404, 
    1.5706,
    0.4009
])
texture_eigenvalues = np.array([
    [0.9967, 0.9921, 0.9887], 
    [0.9484, 0.9674, 0.9534],
    [0.9967, 0.9921, 0.9887]
])

####################################

variables = [
    component_concentrations,
    rotation_axes,
    rotation_angles,
    texture_eigenvalues
]
texture_coefficients_original = tex.tc(odata, 3)
texture_coefficients_central = tex.tccen(variables)
eps = tex.epsilonplus(
    texture_coefficients_original,
    texture_coefficients_central
)
print('%.4f' % eps)

0.5576
